default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: alpha-blog

test:
  <<: *default
  database: alpha_test

production:
  <<: *default
  database: alpha_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
